# Generated by Django 3.1 on 2024-06-06 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usernet',
            options={},
        ),
        migrations.AlterModelManagers(
            name='usernet',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='usernet',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='usernet',
            name='email',
        ),
        migrations.RemoveField(
            model_name='usernet',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='usernet',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='usernet',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='usernet',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='usernet',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='usernet',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='usernet',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='usernet',
            name='username',
        ),
    ]
