# Generated by Django 3.1 on 2024-06-10 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20240606_0637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernet',
            name='github',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
